**SISTEMA DE RECOMENDACION**

**CURSO : PROTOTIPADO DE APLICACIONES DE INTELIGENCIA ARTIFICIAL**

**INSTRUCTOR : MOISÃ‰S EVANGELISTA GAMARRA**

dataset tomado de: https://www.kaggle.com/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

**1.- DESCARGA DE DATOS**

In [3]:
import pandas as pd

imdb = pd.read_csv("/content/sample_data/imdb_top_1000.csv")
imdb.head(10)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
6,https://m.media-amazon.com/images/M/MV5BNGNhMD...,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762"
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
9,https://m.media-amazon.com/images/M/MV5BMmEzNT...,Fight Club,1999,A,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"37,030,102"

** 2.- PREPARACIÃ“N DE DATOS **

 Seleccionar las caracterÃ­sticas de la pelÃ­cula.

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline


# Filter data
##keep_cols = ['Genre', 'Director', 'Star1', 'Star2']
keep_cols = ['Genre', 'Director']
imdb_filtered = imdb.loc[:,keep_cols]

## Pipeline: Es un conjunto de tareas que ocurren en secuencia, 
## donde la salida de una tarea se convierte en la entrada de la siguiente,
## hasta que genera el producto final al final.

# Create pipeline for numerical variables
numeric_pipe = Pipeline([
    ('scaler', StandardScaler())
    ])

# Create pipeline for categorical variable
categorical_pipe = Pipeline([
    ('encoder', OneHotEncoder(drop = 'first'))
    ])

# Create ColumnTransform
col_transf = ColumnTransformer([
    ('numeric', numeric_pipe, imdb_filtered._get_numeric_data().columns.tolist()),
    ('categoric', categorical_pipe, imdb_filtered.select_dtypes('object').columns.tolist()) 
    ])

col_transf_fit = col_transf.fit(imdb_filtered)
imdb_filtered_transf = col_transf_fit.transform(imdb_filtered)
imdb_filtered_transf

<1000x748 sparse matrix of type '<class 'numpy.float64'>'
	with 1994 stored elements in Compressed Sparse Row format>

In [5]:
## KNN= Busca en las observaciones mÃ¡s cercanas a la que se estÃ¡ tratando de predecir y 
## clasifica el punto de interÃ©s basado en la mayorÃ­a de datos que le rodean
from sklearn.neighbors import NearestNeighbors

n_neighbors=5

nneighbors = NearestNeighbors(n_neighbors = n_neighbors, metric = 'cosine').fit(imdb_filtered_transf)

In [6]:
dif, ind = nneighbors.kneighbors(imdb_filtered_transf[1])

##print("Liked Film")
##print("="*80)
imdb.loc[ind[0][0], :]
print("Recommended Films")
##print("="*80)
imdb.loc[ind[0][0:], :]

Recommended Films

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
974,https://m.media-amazon.com/images/M/MV5BNWFlYW...,The Godfather: Part III,1990,A,162 min,"Crime, Drama",7.6,"Follows Michael Corleone, now in his 60s, as h...",60.0,Francis Ford Coppola,Al Pacino,Diane Keaton,Andy Garcia,Talia Shire,359809,"66,666,062"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
180,https://m.media-amazon.com/images/M/MV5BNmVmYz...,To Kill a Mockingbird,1962,U,129 min,"Crime, Drama",8.2,"Atticus Finch, a lawyer in the Depression-era ...",88.0,Robert Mulligan,Gregory Peck,John Megna,Frank Overton,Rosemary Murphy,293811,NaN
480,https://m.media-amazon.com/images/M/MV5BYTRkMD...,Bir Zamanlar Anadolu'da,2011,NaN,157 min,"Crime, Drama",7.9,A group of men set out in search of a dead bod...,82.0,Nuri Bilge Ceylan,Muhammet Uzuner,Yilmaz Erdogan,Taner Birsel,Ahmet MÃ¼mtaz Taylan,41995,"138,730"